//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MrBarber.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Agendamento
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Agendamento()
        {
            this.Faturas = new HashSet<Fatura>();
        }
    
        public System.DateTime DataInicio { get; set; }
        public string Estado { get; set; }
        public int Cliente { get; set; }
        public int Funcionario { get; set; }
        public int Servico { get; set; }
        public string Reclamacao { get; set; }
    
        public virtual Cliente Cliente1 { get; set; }
        public virtual Funcionario Funcionario1 { get; set; }
        public virtual Servico Servico1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Fatura> Faturas { get; set; }
    }
}
