//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MrBarber.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Cliente
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Cliente()
        {
            this.Agendamentoes = new HashSet<Agendamento>();
            this.Recomendacaos = new HashSet<Recomendacao>();
        }
    
        public int idCliente { get; set; }
        public string Nome { get; set; }
        public System.DateTime DataNascimento { get; set; }
        public int ContactoTelefonico { get; set; }
        public string Email { get; set; }
        public string Password { get; set; }
        public int NIF { get; set; }
        public string CodigoProm { get; set; }
        public string CodigoAmigo { get; set; }
        public int Pontos { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Agendamento> Agendamentoes { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Recomendacao> Recomendacaos { get; set; }
    }
}
