//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MrBarber.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Fatura
    {
        public int idFatura { get; set; }
        public decimal PrecoTotal { get; set; }
        public string CodigoProm { get; set; }
        public System.DateTime DataInicioReal { get; set; }
        public System.DateTime DataFinalReal { get; set; }
        public Nullable<int> Agendamento { get; set; }
    
        public virtual Agendamento Agendamento1 { get; set; }
    }
}
