//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MrBarber.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Funcionario
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Funcionario()
        {
            this.Agendamentoes = new HashSet<Agendamento>();
        }
    
        public int idFuncionario { get; set; }
        public string Nome { get; set; }
        public int ContactoTelefonico { get; set; }
        public string Email { get; set; }
        public string Password { get; set; }
        public int Localizacao { get; set; }
        public byte[] Ativo { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Agendamento> Agendamentoes { get; set; }
        public virtual Localizacao Localizacao1 { get; set; }
    }
}
